<div class="contextmenu" id="file-menu">
    <div
      class="menuitem file-related action-see only-for-file only-for-readable">
        Voir <span class="floatRight">entrée</span>
    </div>
    <div class="menuitem file-related action-edit
               only-for-file only-for-readable only-for-writable only-for-text">
        Éditer <span class="floatRight">Maj-entrée</span>
    </div>
    <hr class="file-related only-for-file">
    <div class="menuitem file-related action-rename only-for-writable">
        Renommer ... <span class="floatRight">F2</span>
    </div>
    <hr>
    <div class="menuitem file-related action-delete only-for-writable">
        Supprimer <span class="file-related only-for-dir">récursivement</span> ...
        <span class="floatRight">Suppr</span>
    </div>
</div>

